### ISSUE TITLE
Note about age seeking capabilities

### ISSUE THREAD

**Issue by FiloSottile** [ANSSI-FR/MLA#1]
It's nice to see that the design of the encryption layer converged with age's design.

>  age could be used jointly with an archive format to provide encryption, but lack seeking capabilities and integration with the inner archive format

I saw this note about age in the README and wanted to mention that the age format is seekable pretty much in the same way as yours, unless I misunderstand what you mean. (The rest of the note is obviously correct, age is only an encryption layer.)

**Comment by commial** [comment]
Hello,

Thanks for pointing it out! I've totally missed it.
#3 should fixes it.

Is the resulting note fair enough?

**Comment by commial** [comment]
I finally merged it. Please re-open the issue if you have any additional comment

**Comment by FiloSottile** [comment]
Thank you! Looks good to me, age is definitely not integrated with the archive layer. 👍
