### ISSUE TITLE
cannot build it on windows 10

### ISSUE THREAD

**Issue by omac777** [ANSSI-FR/MLA#10]
On Centos 7, Centos 8 or Fedora Rawhide.
```
Assuming you have rust installed via https://rustup.rs
git clone https://github.com/ANSSI-FR/MLA.git
dnf install clang llvm llvm-devel
cd MLA
cargo build --release
```

On windows 10 however, it produces an error which I have attached the build output.
```
   Compiling afl v0.8.0
error[E0433]: failed to resolve: could not find `BaseDirectories` in `xdg`
 --> C:\Users\davidm\.cargo\registry\src\github.com-1ecc6299db9ec823\afl-0.8.0\src\common.rs:9:10
  |
9 |     xdg::BaseDirectories::with_prefix(prefix).unwrap()
  |          ^^^^^^^^^^^^^^^ could not find `BaseDirectories` in `xdg`

error[E0412]: cannot find type `BaseDirectories` in crate `xdg`
 --> C:\Users\davidm\.cargo\registry\src\github.com-1ecc6299db9ec823\afl-0.8.0\src\common.rs:5:22
  |
5 | fn xdg_dir() -> xdg::BaseDirectories {
  |                      ^^^^^^^^^^^^^^^ not found in `xdg`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0412, E0433.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `afl`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

```

[myMLARWin10BuildNotes.txt](https://github.com/ANSSI-FR/MLA/files/4976238/myMLARWin10BuildNotes.txt)

**Comment by commial** [comment]
Hello,

This is likely due to the `afl` compilation (from the `mla-fuzz-afl` package).
If you don't need the fuzzing part (useful only for testing / reliability purpose), you can compile with:
`cargo build --all --exclude mla-fuzz-afl`.

According to the [CI tests](https://github.com/ANSSI-FR/MLA/runs/907458418), compiling this way and the associated tests should work on Windows.

**Comment by commial** [comment]
As I understand from your "thumb-up" that is solves your issue, I'm closing it. Please re-open if i'm wrong.
