### ISSUE TITLE
please accept source directories and standard input as input for fetching file listings to archive into the .mla

### ISSUE THREAD

**Issue by omac777** [ANSSI-FR/MLA#11]
When I performed:
```
# note this generates key and key.pub
mlar keygen key

# now plunk in source directories to archive into .mla
mlar create -p key.pub -o ./ghidra_9.0.4.mla ./ghidra_9.0.4/`
```

I received the following error:
```
./ghidra_9.0.4/
[!] Command ended with error: IOError(Os { code: 21, kind: Other, message: "Is a directory" })
```

I was expecting to be able to pass in not only individual files as input, but also input source directories, yet I could not.
Please make mlar accept source directories as input.

Also, when we have thousands if not millions of files to list to include into the archive.  We certainly can't list these files on one command-line.
Please have mlar provide another switch accepting an input file list. i.e.
```
find ./ghidra_9.0.4/ -type f -print >myInputFileList.txt
mlar create -p key.pub -o ./ghidra_9.0.4.mla  --filelist myInputFileList.txt
```

Please have mlar accept standard input as an input file list. i.e.
```
find ./ghidra_9.0.4/ -type f -print | mlar create -p key.pub -o ./ghidra_9.0.4.mla --filelist -
```

You might even be best served by some kind of mlar stream daemon, you create for a particular .mla.
Then you may send different file archive requests into that mlar stream daemon in parallel for going the necessity of preparing a file list before hand since you may invoke an archive request as you hit a new file you want to archive when walking the directory tree.  Even the directory tree walking within rust may be done in parallel.

**Comment by commial** [comment]
Hello,

Thanks for the suggestion. I've opened an issue to track this feature request #15.

Regarding the daemon, it would probably make the code of `mlar` too complex; I would like to keep it simple, and working on the different OS.
