### ISSUE TITLE
Please add to mlar CLI the "append file to .mla" capability

### ISSUE THREAD

**Issue by omac777** [ANSSI-FR/MLA#13]
I created an .mla archive:
```
mlar create -p key.pub -o sRgbdSpencAnim.mla sRgbdSpencAnim/*.png
mlar list -k key --input sRgbdSpencAnim.mla
```

But when I attempted to append another file to it via the CLI, there was no capability to do that.
Please add another "--append-file" switch which would essentially call your existing MLA API start_file/append_file_content/end_file.

**Comment by commial** [comment]
In the design of MLA, when an archive is "finalized", we cannot add new files to it. This allow the format to append a footer at the end with only the information needed for quick accesses.

Modifying this paradigm would imply recovering some of the archive writer data-structures (and then, saving more information in the footer). It also means either "going back in the file stream", which is against MLA design, or adding some information to say "actually, there is more of it". This could lead to some class of attacks, and would certainly make the MLA design more complex.

As I don't have a clever way to do it for now, it is not implemented. It might be re-considered in the future.
