### ISSUE TITLE
Python binding support

### ISSUE THREAD

**Issue by commial** [ANSSI-FR/MLA#139]
It would be nice to have MLA bindings for Python.
IMHO, there are 2 main ways to achieve it:

* Rust to Python, based on Pyo3
* Reusing the available Rust-to-C binding, with PyBind11

Solution 2 is likely the simplest. Write binding is already available, and #123 will provides read binding.

**Comment by jbgalet** [comment]
I have a PyBind11 binding ready to push, just waiting for the C read bindings to be merged ;)
