### ISSUE TITLE
Please add to mlar CLI "--append-directory" switch to recursively append files from specified target source directory

### ISSUE THREAD

**Issue by omac777** [ANSSI-FR/MLA#14]
So after creating the following .mla archive:
```
mlar create -p key.pub -o sRgbdSpencAnim.mla sRgbdSpencAnim/*.png
mlar list -k key --input sRgbdSpencAnim.mla
```

I would love to be able to append another directory like this:
```
mlar append -p key.pub -o sRgbdSpencAnim.mla --append-directory sRgbdSpencAnim2/
```

Even better I would love to be able to pass an entire list of directories to append using an input directory list.
This would be more efficient for appending thousands/millions of directories to an .mla:
```
mlar append -p key.pub -o sRgbdSpencAnim.mla --append-input-directory-list inputdirlist.txt
```

You could also possibly allow for fetching that list of directories to append from standard input:
```
find blah/ -type d -print |mlar append -p key.pub -o sRgbdSpencAnim.mla --append-input-directory-list -
```

Related to this discussion of appending specific files to the .mla archive in the same manner:
```
mlar append -p key.pub -o sRgbdSpencAnim.mla --append-input-file-list inputfilelist.txt
```
and
```
find blah/ -type f -print |mlar append -p key.pub -o sRgbdSpencAnim.mla --append-input-file-list -
```

Thank you for listening

**Comment by commial** [comment]
This is not possible for now, for the same reasons than #13.
If I correctly understand your needs, it should be fixed by #15.

I'm closing this issue, please re-open if they're any misunderstanding.
