### ISSUE TITLE
AuthenticatedDecryptionWrongTag error

### ISSUE THREAD

**Issue by msalvago** [ANSSI-FR/MLA#142]
I have run a basic piece of code in which I encrypt a file and then I try to read it. Although the encryption works fine, when I try to read the file, I get the following error:

IOError(Custom { kind: Other, error: "AuthenticatedDecryptionWrongTag" })

I've created the keypair using mlar with the following command:

`mlar keygen key`

I wonder what is exactly causing the error, because I guess it should not be a problem with the key. The code I have run for reading the file is the following:

`// Get the private key
    let private_key = parse_openssl_25519_privkey(PRIV_KEY).unwrap();
    // Specify the key for the Reader
    let mut config = ArchiveReaderConfig::new();
    config.add_private_keys(&[private_key]);

    let buf = io::Cursor::new(DATA);
    match ArchiveReader::from_config(buf, config) {
        Ok(mut mla_read) =>{
            // Get a file
            match mla_read.get_file(String::from("DSC05176.JPG")) {
                Ok(file) => {
                    match file {
                        Some(mut file_info) => {
                            // Get back its filename, size, and data
                            println!("{} ({} bytes)", file_info.filename, file_info.size);
                            let mut output = Vec::new();
                            std::io::copy(&mut file_info.data, &mut output).unwrap();
                            // Get back the list of files in the archive:
                            for fname in mla_read.list_files().unwrap() {
                                println!("{}", fname);
                            }
                        }
                        None => println!("File not found in mla file")
                    }
                }
                Err(e) => println!("Error getting file {}", e)
            };
        }
        Err(e) => println!("Error in mla_read {}", e)
    };`

Do you have any idea what could cause this error?

**Comment by commial** [comment]
Hello,

I've not been able to reproduce the issue.

Dummy question, but I've have to ask: did you encrypt with the public part of your `key`, ie. `key.pub`?

To further debug it:

- are you able to reproduce it with a different set of key? of files?
- are you able to list the files in the archive, or is the error already raised at that time?
- at which line exactly the error is raised?

**Comment by commial** [comment]
I'm closing this issue for now. Feel free to re-open it if you have new elements
