### ISSUE TITLE
Platform-independent path handling

### ISSUE THREAD

**Issue by timosluis** [ANSSI-FR/MLA#186]
I have created an archive on Windows using mlar, and this results in files in directories being added with the Windows convention for path notation, so `foo\bar\baz.txt`, instead of `foo/bar/baz.txt` on other platforms. Then because `ArchiveReader::get_file` takes a `String` as parameter, I need to make sure that I use the path notation that matches that of the platform on which the archive was made. This can become quite inconvenient when writing code which should work on different platforms. I see two possible solutions for my particular issue:
- mlar needs to store files with a portable path notation (which is arguably just a workaround)
- Change `ArchiveReader::get_file` so it takes a `Path`-like object for locating files

To achieve this, we can maybe use the [relative-path](https://crates.io/crates/relative-path) crate, or the [unix_path](https://crates.io/crates/unix_path) crate. Both of these crates provide consistent handling of paths, regardless of platform. I haven't dug too deep in the codebase of mla, but maybe both solutions are necessary to provide true platform-independent path handling.

I could probably work around this issue myself by using another tool for creating mla archives, ensuring it does use platform-independent path notation, but thought I might share my experience with you, so maybe we can come to a solution that works for everyone. Please let me know your thoughts on this proposal!

**Comment by commial** [comment]
First, thanks for your interest regarding MLA.

As stated in the "API Guideline":
> The goal is to keep the file format simple enough, and to leave the complexity to the code using it. Things such as permissions, ownership, etc. are hard to guarantee over several OSes and filesystems; and lead to higher complexity, for example in tar. For the same reasons, / or \ do not have any significance in filename; it is up to the user to choose how to handle them (are there namespaces? directories in Windows style? etc.).
> 
> If one still wants to have associated metadata for its own use case, the recommended way is to embed an additional file in the archive containing the needed metadata.

It might be seen as a "coward argumentation", but for now, I rather prefer having a simple format and leave the complexity and OS-specifics design choices to the library's user. The storage is then an association of `String` -> `binary data`, whatever the `String` is.

As a result, if you want to have your code handling path in a OS agnostic way, it is up to the implementor. Others questions may arise: what about leading `/`? Do they represent the root path, or the relative root path? What about `../`? What about data with a filename ending with a `/`, should one drop them, create a directory for them, ... ? Etc.

In the `mlar` project, which is a client of the MLA library, the choice has been made to consider `/` and `\\` as directory separator on extraction and archive creation. But this is specific to `mlar`.

I hope I've answered your question, do not hesitate to re-open the issue if not.
