### ISSUE TITLE
Jingle MLA

### ISSUE THREAD

**Issue by garaulettabri-2912** [ANSSI-FR/MLA#225]
Merci pour cet outil vraiment très élégant je pense qu'il faudrait ajouté un petit jingle qui pourrait être joué par ex lors du déchiffrement d'une archive MLA

En PJ une proposition de jingle que je peux retravailler si nécessaire si ça convient pas

Merci encore pour ce projet

G.Abri

https://github.com/user-attachments/assets/f07e45ac-e20e-45f7-a469-667b4ebc5d52

**Comment by garaulettabri-2912** [comment]
Peut-etre qu'il faudrait ajouter de l'autotune vous en pensez quoi

**Comment by garaulettabri-2912** [comment]
Re j'ai retravaillé un peu le projet avec des potes et on a fait un truc pas mal dites-moi si ça vous va

https://github.com/user-attachments/assets/aa02fd58-43ab-448c-8a4a-826eca991420

**Comment by ComradeAERGO** [comment]
On la veut sur Spotify maintenant
