### ISSUE TITLE
keys from smartcard ?

### ISSUE THREAD

**Issue by aglossa** [ANSSI-FR/MLA#66]
Do you have in roadmap to use smartcard with ECC certificates, as source of keys ?
PKCS11 in *nix world, WinScard in Windows

**Comment by commial** [comment]
Hello,

There is no specific plan regarding the integration of smartcard for now. But it would sure be a nice feature of `mlar`.

As you mention, there is a need to use several libraries to support the functionality on different OS. There is then an additional cost for developing, testing and maintaining this feature. Additionally, I have no idea of the current state of the Rust support for smartcard, on the different OS.
