### ISSUE TITLE
comparison

### ISSUE THREAD

**Issue by aglossa** [ANSSI-FR/MLA#67]
What is the differences / bonus / malus with 
https://github.com/FiloSottile/age and spec https://age-encryption.org/v1

**Comment by commial** [comment]
Quoting the README: (https://github.com/ANSSI-FR/MLA#is-a-new-format-really-required)

> any archive + age: age could be used jointly with an archive format to provide encryption, but would likely lack integration with the inner archive format

I'm not an expert of "age", but it seems to me the goals are not quite the same. What they gain in generality ("age" could work with any file format) might be loss in integration with the inner format, such as streaming / repairing / seeking / etc. capacity that MLA provides.
