### ISSUE TITLE
This crate is growing stale. Please update

### ISSUE THREAD

**Issue by STashakkori** [ANSSI-FR/MLA#98]
aes-ctr and aes-gcm are both deprecated and the features rolled into aes, which is on version 0.7.5 and this crate is on version 0.5. Please update this crate. Updating crypto is important for security crates and not doing so casts doubt on a crate's viability.

**Comment by commial** [comment]
I agree with you, security dependencies have to be updated. From what I understand, RustCrypto crates were in a rather big refactoring these days, and I was waiting having them in a "stable" state.
As you noticed, `aes-ctr` and `aes-gcm` (which is only used for test in MLA) are now deprecated.
I'm now trying to understand what I should do with the new crate layout, as I'm not sure they actually merged in the crate `aes` (but rather were dispatched in other crates).

If you have a better understanding than me on this layout, a PR is always welcomed. It would greatly speed up this whole process.
